import express from 'express';
import dotenv from 'dotenv';  
import cors from 'cors';
import bodyParser from 'body-parser';
import cookieParser from 'cookie-parser';
import { connection } from './db/connection.js';
import authRoutes from './routes/auth.route.js';
import shopRoutes from './routes/shop.route.js';
import productRoutes from './routes/product.route.js';
import eventRoutes from './routes/event.route.js';
import couponRoutes from './routes/couponCode.route.js';
import paymentRoutes from './routes/payment.route.js';
import orderRoutes from './routes/order.route.js';
import conversationRoutes from './routes/conversation.route.js';
import messageRoutes from './routes/message.route.js';
import cloudinary from 'cloudinary';

dotenv.config();
const app = express();
const PORT = process.env.PORT || 5000;